name: aos-signature
version: 0.2
synopsis: An implementation of the AOS signatures
description: An implementation of 1-out-of-n signatures from a variety of keys
maintainer: Adjoint Inc (info@adjoint.io)
license: Apache
github: adjoint-io/aos-signature
category: Cryptography

extra-source-files:
- README.md

flags:
  static:
    description: Emit statically-linked binary
    manual: False
    default: False

  optimized:
    description: Perform compiler optimizations
    manual: False
    default: False

dependencies:
  # Prelude
  - base >= 4.7 && < 5
  - protolude  >= 0.2
  - cryptonite
  - bytestring
  - random
  - memory
  - mtl

library:
  source-dirs: src

  ghc-options:
    -fwarn-tabs
    -fwarn-incomplete-patterns
    -fwarn-incomplete-record-updates
    -fwarn-redundant-constraints
    -fwarn-implicit-prelude
    -fwarn-overflowed-literals
    -fwarn-orphans
    -fwarn-identities
    -fwarn-dodgy-exports
    -fwarn-dodgy-imports
    -fwarn-duplicate-exports
    -fwarn-overlapping-patterns
    -fwarn-missing-fields
    -fwarn-missing-methods
    -fwarn-missing-signatures
    -fwarn-noncanonical-monad-instances
    -fwarn-unused-pattern-binds
    -fwarn-unused-type-patterns
    -fwarn-unrecognised-pragmas
    -fwarn-wrong-do-bind
    -fno-warn-name-shadowing
    -fno-warn-unused-binds
    -fno-warn-unused-matches
    -fno-warn-unused-do-bind

  default-extensions:
    - LambdaCase
    - RecordWildCards
    - OverloadedStrings
    - NoImplicitPrelude
    - FlexibleInstances

  exposed-modules:
    - LSAG


tests:
  aos-signature-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aos-signature
    - QuickCheck
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    default-extensions:
    - LambdaCase
    - RecordWildCards
    - OverloadedStrings
    - NoImplicitPrelude
    - FlexibleInstances
